/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  common\MotionProfiles.cpp
 *  subm:  Heater
 *  model: heater
 *  expmt: heater
 *  date:  November 1, 2018
 *  time:  5:48:32 PM
 *  user:  Johannes Burger
 *  from:  Cooll Sustainable Energy Solutions BV, 20-sim 4.7 Professional Single
 *  build: 4.7.1.8902
 **********************************************************/

/* This file implements the functions necessary for motion profiles
   functions
*/


