/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  common\MotionProfiles.h
 *  model: heater
 *  expmt: heater
 *  date:  October 26, 2018
 *  time:  3:48:46 PM
 *  user:  Johannes Burger
 *  from:  Cooll Sustainable Energy Solutions BV, 20-sim 4.7 Professional Single
 *  build: 4.7.1.8902
 **********************************************************/

/* This file defines the functions necessary for motion profiles
   functions
*/
