/**********************************************************
 * This file is generated by 20-sim C++ Code Generator
 *
 *  file:  test_Heater.cpp
 *  subm:  Heater
 *  model: heater
 *  expmt: heater
 *  date:  October 31, 2018
 *  time:  5:43:36 PM
 *  user:  Johannes Burger
 *  from:  Cooll Sustainable Energy Solutions BV, 20-sim 4.7 Professional Single
 *  build: 4.7.1.8902
 **********************************************************/

/* This file is a demo application of how the submodel function can
 * be used. It uses the global time variables that are used by both
 * the submodel and the integration method.
 *
 * PLEASE NOTE: THIS IS AN EXAMPLE WHERE ALL INPUTS ARE ZERO !
 * USE YOUR OWN INPUTS INSTEAD!! ALSO THE SUBMODEL MIGHT SIMPLY
 * NOT WORK CORRECTLY WITH INPUTS THAT ARE ZERO.
 */

#include <stdio.h>

/* 20-sim submodel class include file */
#include "Heater.h"

/* the main function */
int main()
{
	XXDouble u [3 + 1];
	XXDouble y [11 + 1];

	/* initialize the inputs and outputs with correct initial values */
	u[0] = 0.0;		/* dm_water {kg/s} */
	u[1] = 0.0;		/* P_natural_gas {W} */
	u[2] = 0.0;		/* Tin */

	y[0] = 0.0;		/* Tout */
	y[1] = 0.0;		/* TSteel1 {K} */
	y[2] = 0.0;		/* TSteel2 {K} */
	y[3] = 0.0;		/* TSteel3 {K} */
	y[4] = 0.0;		/* TSteel4 {K} */
	y[5] = 0.0;		/* TSteel5 {K} */
	y[6] = 0.0;		/* TWater1 {K} */
	y[7] = 0.0;		/* TWater2 {K} */
	y[8] = 0.0;		/* TWater3 {K} */
	y[9] = 0.0;		/* TWater4 {K} */
	y[10] = 0.0;		/* TWater5 {K} */


	Heater my20simSubmodel;

	/* initialize the submodel itself and calculate the outputs for t=0.0 */
	my20simSubmodel.Initialize(u, y, 0.0);
	printf("Time: %f\n", my20simSubmodel.GetTime() );

	/* simple loop, the time is incremented by the integration method */
	while (my20simSubmodel.state != Heater::finished)
	{
		/* call the submodel to calculate the output */
		my20simSubmodel.Calculate (u, y);
		printf("Time: %f\n", my20simSubmodel.GetTime() );
	}

	/* perform the final calculations */
	my20simSubmodel.Terminate (u, y);

	/* and we are done */
	return 0;
}

